//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class acceso
    {
        public string idacceso { get; set; }
        public int idusuario { get; set; }
        public Nullable<int> idmodulo { get; set; }
        public string codopcion { get; set; }
        public Nullable<int> ver { get; set; }
        public Nullable<int> grabar { get; set; }
        public Nullable<int> anular { get; set; }
        public Nullable<System.DateTime> fecregistro { get; set; }
        public Nullable<System.DateTime> fecmodificacion { get; set; }
    }
}
