//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int idasistencia { get; set; }
        public string  fecha { get; set; }
        public string horainicio { get; set; }
        public string horasalida { get; set; }
        public int idtrabajador { get; set; }
        public string empresa { get; set; }
        public Nullable<System.DateTime> fecregistro { get; set; }
        public Nullable<System.DateTime> fecmodificacion { get; set; }
        public string codsuc { get; set; }
        public string userRegistro { get; set; }
        public string userModificacion { get; set; }
        public string nombre { get; set; }
          public string dni { get; set; }
          public string deshabilitado { get; set; }
        
     

     
    }
}
