//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acceso> acceso { get; set; }
        public DbSet<asistencia> asistencia { get; set; }
        public DbSet<cita> cita { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<indeseado> indeseado { get; set; }
        public DbSet<modulo> modulo { get; set; }
        public DbSet<perfil> perfil { get; set; }
        public DbSet<seguro> seguro { get; set; }
        public DbSet<sucursal> sucursal { get; set; }
        public DbSet<tbprueba> tbprueba { get; set; }
        public DbSet<trabajador> trabajador { get; set; }
        public DbSet<trabajadorAuditoria> trabajadorAuditoria { get; set; }
        //public DbSet<visitante> visitante { get; set; }
        public DbSet<cargaVehicular> cargaVehicular { get; set; }
    }
}
