//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbprueba
    {
        public int idprueba { get; set; }
        public Nullable<System.DateTime> fecd { get; set; }
        public Nullable<System.DateTime> fecdt { get; set; }
        public string nomusu { get; set; }
    }
}
