//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajadorAuditoria
    {
        public int idtrabaud { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public string cargo { get; set; }
        public string area { get; set; }
        public int idempresa { get; set; }
        public int idtrabajador { get; set; }
        public Nullable<System.DateTime> feccreacion { get; set; }
    }
}
