//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImudesaSystem_v4_.Models.Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitante
    {
        public int idvisitante { get; set; }
        public string fecha { get; set; }
        public string horaentrada { get; set; }
        public string horasalida { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public string destino { get; set; }
        public string encargado { get; set; }
        public string empresa_proveniente { get; set; }
        public string observacion { get; set; }
        public Nullable<int> nroasignado { get; set; }
        public string fechaRegistro { get; set; }
        public string codsuc { get; set; }
        public string userRegistro { get; set; }
        public string habilitado { get; set; }

        
    }
}
